# Generated by Django 3.2.19 on 2023-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0002_auto_20230524_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
