# Generated by Django 3.2.19 on 2023-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0003_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='seed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
