# Generated by Django 3.2.19 on 2023-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0007_auto_20230524_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='num_teams',
            field=models.IntegerField(choices=[(16, 16), (32, 32), (64, 64)], default=16),
        ),
    ]
