# Generated by Django 3.2.19 on 2023-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0010_alter_bracket_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='created_by',
        ),
        migrations.AddField(
            model_name='bracket',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
