# Generated by Django 3.2.19 on 2023-05-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0011_auto_20230525_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bracket.bracket'),
            preserve_default=False,
        ),
    ]
