# Generated by Django 3.2.19 on 2023-05-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0013_auto_20230525_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='parent_match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_match', to='Bracket.match'),
        ),
    ]
