# Generated by Django 4.1.7 on 2023-06-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0031_currentround'),
        ('Bracket', '0019_alter_bracket_num_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_points',
        ),
        migrations.AddField(
            model_name='match',
            name='quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.quiz'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
