# Generated by Django 4.1.7 on 2023-06-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0031_currentround'),
        ('Bracket', '0020_remove_match_team1_remove_match_team1_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='quiz',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Records.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='Records.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
