# Generated by Django 4.1.7 on 2023-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0021_remove_match_quiz_match_team1_match_team1_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_seed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_seed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
