# Generated by Django 4.1.7 on 2023-06-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Records', '0025_alter_askedquestion_individual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveScoreKeepers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.quiz')),
                ('scorekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.individual')),
            ],
        ),
    ]
