# Generated by Django 4.1.7 on 2023-03-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.individual')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.team')),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.quiz')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.individual')),
            ],
        ),
    ]
