# Generated by Django 4.1.7 on 2023-03-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_remove_individual_team_individual_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default='Summer Spectacular', max_length=100),
            preserve_default=False,
        ),
    ]
