# Generated by Django 4.1.7 on 2023-03-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0007_quiz_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.room'),
        ),
    ]
