# Generated by Django 4.1.7 on 2023-03-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0010_rename_room_quiz_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='event',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quizmaster',
        ),
        migrations.RemoveField(
            model_name='quizparticipants',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizparticipants',
            name='team',
        ),
        migrations.DeleteModel(
            name='AskedQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizParticipants',
        ),
    ]
