# Generated by Django 4.1.7 on 2023-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0012_quiz_quizparticipants_askedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='round',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
