# Generated by Django 4.1.7 on 2023-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0014_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedquestion',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
