# Generated by Django 4.1.7 on 2023-03-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0016_league_season_league_team_season_leaguemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.league'),
        ),
    ]
