# Generated by Django 4.1.7 on 2023-03-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0017_alter_season_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedquestion',
            name='bonusDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='bonusValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='value',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
