# Generated by Django 4.1.7 on 2023-03-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0018_askedquestion_bonusdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizparticipants',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.team'),
        ),
    ]
