# Generated by Django 4.1.7 on 2023-06-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0020_individual_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='birthday',
            field=models.DateField(blank=True, default=None, verbose_name=''),
        ),
    ]
