# Generated by Django 4.1.7 on 2023-06-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0022_rename_year_season_start_date_remove_season_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
