# Generated by Django 4.1.7 on 2023-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0025_alter_askedquestion_individual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askedquestion',
            old_name='ruleing',
            new_name='ruling',
        ),
    ]
