# Generated by Django 4.1.7 on 2023-06-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0028_quiz_scorekeeper_alter_quiz_quizmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='individual',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.individual'),
        ),
    ]
