# Generated by Django 4.1.7 on 2023-06-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0029_quiz_isvalidated_alter_askedquestion_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
