# Generated by Django 4.1.7 on 2023-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0031_currentround'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
            preserve_default=False,
        ),
    ]
