# Generated by Django 4.1.7 on 2023-06-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Records', '0034_team_division'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='team',
        #     name='type',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        migrations.AlterField(
            model_name='quiz',
            name='round',
            field=models.IntegerField(),
        ),
    ]
