# Generated by Django 4.1.7 on 2023-06-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0036_alter_askedquestion_individual_delete_currentround'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_teams',
            field=models.IntegerField(default=3),
        ),
    ]
