# Generated by Django 4.1.7 on 2023-07-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_teams', models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64)], default=16)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('team1_seed', models.IntegerField(blank=True, default=None, null=True)),
                ('team2_seed', models.IntegerField(blank=True, default=None, null=True)),
                ('team1_points', models.IntegerField(blank=True, default=None, null=True)),
                ('team2_points', models.IntegerField(blank=True, default=None, null=True)),
                ('is_upper_child', models.BooleanField(default=False)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bracket.bracket')),
                ('parent_match', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_match', to='Bracket.match')),
                ('team1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Records.team')),
                ('team2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='Records.team')),
            ],
        ),
    ]
