# Generated by Django 3.2.19 on 2023-05-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Bracket.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team1_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='Bracket.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
