# Generated by Django 3.2.19 on 2023-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0004_team_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedNumberOfTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teams', models.IntegerField()),
            ],
        ),
    ]
