# Generated by Django 3.2.19 on 2023-05-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0005_allowednumberofteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='num_teams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bracket.allowednumberofteams'),
            preserve_default=False,
        ),
    ]
