# Generated by Django 3.2.19 on 2023-05-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0012_team_bracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bracket',
        ),
        migrations.RemoveField(
            model_name='team',
            name='seed',
        ),
    ]
