# Generated by Django 3.2.19 on 2023-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0014_match_parent_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_seed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_seed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
