# Generated by Django 3.2.19 on 2023-05-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0015_auto_20230530_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.CharField(choices=[('E', 'East'), ('W', 'West'), ('S', 'South'), ('M', 'Midwest')], default=None, max_length=1, null=True),
        ),
    ]
