# Generated by Django 3.2.19 on 2023-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0018_auto_20230602_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='num_teams',
            field=models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64)], default=16),
        ),
    ]
