# Generated by Django 4.1.7 on 2023-07-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('tiebreaker', 'Tiebreaker'), ('normal', 'Normal')], max_length=100, null=True)),
                ('division', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
                ('next_room', models.CharField(max_length=10)),
                ('next_round', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='quizparticipants',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('normal', 'Ok'), ('tiebreaker', 'Tiebreaker')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('tiebreaker', 'Tiebreaker'), ('normal', 'Normal')], default='normal', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Progression',
        ),
        migrations.AddField(
            model_name='quizprogression',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.quiz'),
        ),
    ]
