# Generated by Django 4.1.7 on 2023-07-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.event')),
                ('teams', models.ManyToManyField(to='Records.team')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
    ]
