# Generated by Django 4.2 on 2023-07-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_remove_team_division_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprogression',
            name='next_room',
        ),
        migrations.RemoveField(
            model_name='quizprogression',
            name='next_round',
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_ties',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizprogression',
            name='next_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_division', to='Records.division'),
        ),
        migrations.AddField(
            model_name='quizprogression',
            name='next_quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_quiz', to='Records.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizprogression',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.division'),
        ),
        migrations.AlterField(
            model_name='quizprogression',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.quiz'),
        ),
    ]
