# Generated by Django 4.2 on 2023-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_remove_quizprogression_next_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogression',
            name='allow_ties',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizprogression',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='quizparticipants',
            unique_together={('quiz', 'team')},
        ),
    ]
