# Generated by Django 4.1.7 on 2023-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_season_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Spring Spectacular - 2023', max_length=100),
            preserve_default=False,
        ),
    ]
