# Generated by Django 4.2 on 2023-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0005_alter_quizparticipants_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
    ]
