# Generated by Django 4.2 on 2023-07-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0006_alter_division_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='individuals',
            field=models.ManyToManyField(through='Records.TeamMembership', to='Records.individual'),
        ),
    ]
