# Generated by Django 4.1.7 on 2023-06-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0023_remove_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestion',
            name='individual',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Records.individual'),
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='ruleing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
