# Generated by Django 4.1.7 on 2023-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0026_rename_ruleing_askedquestion_ruling'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orginization',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='leaguemembership',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='quizparticipants',
            name='isValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
