# Generated by Django 4.1.7 on 2023-06-19 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0027_rename_orginization_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='scorekeeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scorekeeper', to='Records.individual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizmaster', to='Records.individual'),
        ),
    ]
