# Generated by Django 4.1.7 on 2023-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0033_alter_individual_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
