# Generated by Django 4.1.7 on 2023-06-29 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0035_team_type_alter_quiz_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestion',
            name='individual',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Records.individual'),
        ),
        migrations.DeleteModel(
            name='CurrentRound',
        ),
    ]
