# Generated by Django 4.1.7 on 2023-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Records', '0037_quiz_num_teams'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='team',
        #     name='type',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
