# Generated by Django 4.1.7 on 2023-06-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Records', '0038_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isTournament',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='team',
        #     name='type',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
