# Generated by Django 4.1.7 on 2023-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0039_event_istournament_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
