from typing import Dict, List, Optional, Tuple

divisions = {
    'B': {
        'A': ['Two Generations', 'parent-child', ['Tom Swinton', None, 'Stacy Lagger ', None]],
        'B': ['Grapes and Figs', None, ['Lydia Pipkin', None, 'Abigail Unger ', None]],
        'C': ['Sufficient Unto the Day', None, ['Joshua Floyd', None, 'Michael Glass ', None]],
        'D': ['Canaan 6', None, ['Ryan Baker', None, 'Osman Nava ', None]],
        'E': ['He that Knocketh', None, ['Timothy Vliet', None, 'Elijah Crosby', None]],
        'F': ['Mom, Pop, and Tot', None, ['Jim Davis', None, 'Debbie Davis ', None]],
        'G': ['Pearls of Grace', None, ['Bethany Cutler', None, 'Destiny Wells', None]],
        'H': ['Love is Blind ', None, ['Adam Eastland', None, 'Emma Eastland ', None]],
        'I': ['Victory Violets', None, ['Katie Litke', None, 'Elise Ames ', None]],
        'J': ['The Attaining Twain', None, ['Samuel Unger', None, 'Megan Carnell', None]],
        'K': ['The L.A.M.P.s', None, ['Landyn Marunich', None, 'Amaryssa Paige ', None]],
        'L': ['Yea & Nay', None, ['Andrea Fonte', None, 'Karen McGregor ', None]],
        'M': ['The BelLilies', None, ['Bellhannah Cutler', None, 'Lily Crane', None]],
        'N': ['Cup & Saucer', 'sibling', ['Callum Leys', None, 'Charlotte Leys ', None]],
        'O': ['Canaan 2', None, ['Faith Baker', None, 'Sarah Grace Baker', None]],
        'P': ['No Stinkin Thinkin', None, ['Rachel Carnell', None, 'Charity Unger', None]],
        'Q': ['Mountain Men ', None, ['David Smith', None, 'Matthew Crosby', None]],
        'R': ['The Uttermost Farthings', None, ['Jonathan Rose', None, 'Timothy Rose', None]],
        'S': ['Once Upon a Quiz', None, ['Mark Crosby', None, 'Esther Crosby', None]],
        'T': ['Baby G and Big B', None, ['Gabriel Unger', None, 'Ben Crosby', None]],
        'U': ['Solt and Light ', None, ['Silas Davis', None, 'Daniel Solt', None]],
        'V': ['Canaan 4', None, ['Haley Jensen', None, 'Ariana Howard', None]],
        'W': ['Canaan 8', None, ['Roselyn Delagarza', None, 'Ashleigh F.Slaughter', None]],
        'X': ['Sweet Sassy Molassy', None, ['Abigail Crosby', None, 'Elizabeth Vliet', None]],
        'Y': ['JC x 4', None, ['Matthew Baker', None, 'Nathan Couick ', None]],
        'Z': ['Artsy Smartsy', None, ['Timothy Crosby', None, 'Amelia Wells', None]],
        '#': ['Taking no Thought', None, ['Esther Tricquet', None, 'Bethany Carnell', None]],
    },
    'R': {
        'A': ['Off to a Rocky Start', None, ['Lydia Crosby', None, 'Naomi Floyd ', None]],
        'B': ['Go Up Thou Bald Head', None, ['Eric Carnell', None, 'Jonathan Carnell', None]],
        'C': ['The Lilies of the Field', None, ['Addie Davis', None, 'Faith Fonte', None]],
        'D': ['Canaan 7', None, ['Grace Slaughter', None, 'Abby Jensen ', None]],
        'E': ['Unprofitable Servants ', None, ['Jason Farmer', None, 'John Hall ', None]],
        'F': ['Canaan 1', None, ['Nathan Labit', None, 'Emmanual Nava', None]],
        'G': ['Morning Glories', None, ['Misty Rodriguez', None, 'Mikyla Rodriguez ', None]],
        'H': ['Torches', None, ['Josiah Wells', None, 'Gabriel Ballinger ', None]],
        'I': ['The Peacemakers', None, ['Carrie Whitehead', None, 'Isaac Whitehead', None]],
        'J': ['David and Jonahthan', None, ['David Jones', None, 'Jonah Unger ', None]],
        'K': ['A City on a Hill', None, ['Justus Wells', None, 'Landon Farmer', None]],
        'L': ['The Invincible Blob', None, ['Lucas Whitehead', None, 'Autumn Whitehead ', None]],
        'M': ['Just have Mercy ', None, ['Jeffrey Hall', None, 'Jodi Taylor ', None]],
        'N': ['Bible Detectives', None, ['JJ Moser', None, 'Ben Davis', None]],
        'O': ['The Fill-Ins', None, ['Kati Greene', None, 'Mary Grace Carnell', None]],
        'P': ['Smartees ', None, ['Lydia Ballinger', None, 'Molly Carnell', None]],
        'Q': ['Savory Salt', None, ['Joshua Grimm', None, 'Tammy Grimm', None]],
        'R': ['Walker Squared', None, ['Clay Walker', None, 'Kelsey Walker', None]],
        'S': ['Coaches Squared', None, ['Andrea Phillips', None, 'Susanna Myers', None]],
        'T': ['MG Squared', None, ['Moriah Pipkin', None, 'Grace Carnell', None]],
        'U': ['The Hopping Bunnies ', None, ['Ruthie Davis', None, 'Tirzah Davis', None]],
        'V': ['Canaan 5', None, ['Emma Jensen', None, 'Kelsey Key', None]],
        'W': ['Hi Cs ', None, ['Charlotte Caruthers', None, 'Cassia Caruthers', None]],
        'X': ['Treasure Seekers', None, ['Brigitta Cutler', None, 'Lia Crane', None]],
        'Y': ['Trailblazers', None, ['Josiah Ballinger', None, 'Jaxon Wells ', None]],
        'Z': ['Married yet Single', None, ['Joshua Unger', None, 'Natalie Unger', None]],
        '#': ['Curly Fries', None, ['Micah Floyd', None, 'Abby Glass', None]],
    },
}

quizzes = {
    '101': (('RI', 'RL', 'RO'), ('RM', 'RQ', 'RI'), ('RF', 'RB', 'RD'), ('RH', 'RK', 'RW'), ('RN', 'RX', 'RA'),
            ('RR', 'RE', 'RP'), ('R#', 'RO', 'RU'), ('RN', 'RC', 'RV'), ('RG', 'RL', 'RT'), ('RA', 'RS', 'RJ'),
            ('RP', 'RW', 'R#'), ('RC', 'RW', 'RM'), ('RX', 'RY', 'RZ'), (), (),),
    '102': (('RK', 'RN', 'RQ'), ('RU', 'RY', 'RT'), ('RG', 'R#', 'RE'), ('RF', 'RI', 'RU'), ('RM', 'RZ', 'R#'),
            ('RZ', 'RA', 'RL'), ('RA', 'RP', 'RV'), ('RR', 'RJ', 'RB'), ('RW', 'RA', 'RO'), ('RO', 'RF', 'RX'),
            ('RS', 'RH', 'RL'), ('RD', 'RU', 'RN'), ('RC', 'RD', 'RE'), (), (),),
    '103': (('RR', 'RU', 'RX'), ('RD', 'RH', 'R#'), ('RO', 'RK', 'RM'), ('RC', 'RO', 'RR'), ('RP', 'RT', 'RC'),
            ('RX', 'RB', 'RM'), ('RB', 'RQ', 'RW'), ('RT', 'RI', 'RA'), ('RF', 'RN', 'RS'), ('RP', 'RG', 'RY'),
            ('RC', 'RJ', 'RZ'), ('RE', 'RV', 'RL'), ('RF', 'RG', 'RH'), (), (),),
    '104': (('RJ', 'RM', 'RP'), ('RE', 'RF', 'RA'), ('RX', 'RT', 'RV'), ('RB', 'RN', 'RZ'), ('RK', 'RU', 'RG'),
            ('RS', 'RC', 'RQ'), ('RL', 'RR', 'RF'), ('RL', 'RD', 'RW'), ('RK', 'RY', 'RC'), ('R#', 'RR', 'RI'),
            ('RO', 'RV', 'RB'), ('RY', 'RO', 'RH'), ('RL', 'RM', 'RN'), (), (),),
    '105': (('RS', 'RV', 'RY'), ('RN', 'RO', 'RJ'), ('RZ', 'RS', 'RU'), ('RE', 'RQ', 'RT'), ('RQ', 'RR', 'RD'),
            ('RW', 'RG', 'RI'), ('RX', 'RC', 'RI'), ('RS', 'RK', 'R#'), ('RU', 'RB', 'RP'), ('RQ', 'RH', 'RZ'),
            ('RT', 'RF', 'RM'), ('RK', 'RA', 'RR'), ('R#', 'RA', 'RB'), (), (),),
    '106': (('RA', 'RD', 'RG'), ('RL', 'RP', 'RK'), ('RH', 'RA', 'RC'), ('RG', 'RJ', 'RV'), ('RO', 'RS', 'RE'),
            ('RY', 'R#', 'RN'), ('RZ', 'RE', 'RK'), ('RF', 'RY', 'RQ'), ('RH', 'RM', 'RR'), ('RB', 'RT', 'RK'),
            ('RE', 'RI', 'RY'), ('RX', 'RQ', 'RG'), ('RU', 'RV', 'RW'), (), (),),
    '205': (('RB', 'RE', 'RH'), ('RV', 'RZ', 'RR'), ('RP', 'RI', 'RN'), ('RA', 'RM', 'RY'), ('RJ', 'RW', 'RF'),
            ('RV', 'RF', 'RK'), ('RM', 'RS', 'RG'), ('RH', 'RX', 'RP'), ('RJ', 'RX', 'RE'), ('RU', 'RL', 'RC'),
            ('RD', 'RK', 'RX'), ('RJ', 'R#', 'RT'), ('RO', 'RP', 'RQ'), (), (),),
    '206': (('RT', 'RW', 'RZ'), ('RC', 'RG', 'RB'), ('RQ', 'RJ', 'RL'), ('R#', 'RL', 'RX'), ('RI', 'RV', 'RH'),
            ('RT', 'RD', 'RO'), ('RY', 'RD', 'RJ'), ('RM', 'RE', 'RU'), ('RI', 'RZ', 'RD'), ('RW', 'RN', 'RE'),
            ('RR', 'RG', 'RN'), ('RZ', 'RP', 'RF'), ('RR', 'RS', 'RT'), (), (),),
    '213': (('R#', 'RC', 'RF'), ('RW', 'RX', 'RS'), ('RY', 'RR', 'RW'), ('RD', 'RP', 'RS'), ('RL', 'RY', 'RB'),
            ('RU', 'RH', 'RJ'), ('RN', 'RT', 'RH'), ('RG', 'RZ', 'RO'), ('RV', 'R#', 'RQ'), ('RV', 'RM', 'RD'),
            ('RQ', 'RU', 'RA'), ('RI', 'RB', 'RS'), ('RI', 'RJ', 'RK'), (), (),),
    '202': (('BI', 'BL', 'BO'), ('BM', 'BQ', 'BI'), ('BF', 'BB', 'BD'), ('BH', 'BK', 'BW'), ('BN', 'BX', 'BA'),
            ('BR', 'BE', 'BP'), ('B#', 'BO', 'BU'), ('BN', 'BC', 'BV'), ('BG', 'BL', 'BT'), ('BA', 'BS', 'BJ'),
            ('BP', 'BW', 'B#'), ('BC', 'BW', 'BM'), ('BX', 'BY', 'BZ'), (), (),),
    '203': (('BK', 'BN', 'BQ'), ('BU', 'BY', 'BT'), ('BG', 'B#', 'BE'), ('BF', 'BI', 'BU'), ('BM', 'BZ', 'B#'),
            ('BZ', 'BA', 'BL'), ('BA', 'BP', 'BV'), ('BR', 'BJ', 'BB'), ('BW', 'BA', 'BO'), ('BO', 'BF', 'BX'),
            ('BS', 'BH', 'BL'), ('BD', 'BU', 'BN'), ('BC', 'BD', 'BE'), (), (),),
    '204': (('BR', 'BU', 'BX'), ('BD', 'BH', 'B#'), ('BO', 'BK', 'BM'), ('BC', 'BO', 'BR'), ('BP', 'BT', 'BC'),
            ('BX', 'BB', 'BM'), ('BB', 'BQ', 'BW'), ('BT', 'BI', 'BA'), ('BF', 'BN', 'BS'), ('BP', 'BG', 'BY'),
            ('BC', 'BJ', 'BZ'), ('BE', 'BV', 'BL'), ('BF', 'BG', 'BH'), (), (),),
    '207': (('BJ', 'BM', 'BP'), ('BE', 'BF', 'BA'), ('BX', 'BT', 'BV'), ('BB', 'BN', 'BZ'), ('BK', 'BU', 'BG'),
            ('BS', 'BC', 'BQ'), ('BL', 'BR', 'BF'), ('BL', 'BD', 'BW'), ('BK', 'BY', 'BC'), ('B#', 'BR', 'BI'),
            ('BO', 'BV', 'BB'), ('BY', 'BO', 'BH'), ('BL', 'BM', 'BN'), (), (),),
    '208': (('BS', 'BV', 'BY'), ('BN', 'BO', 'BJ'), ('BZ', 'BS', 'BU'), ('BE', 'BQ', 'BT'), ('BQ', 'BR', 'BD'),
            ('BW', 'BG', 'BI'), ('BX', 'BC', 'BI'), ('BS', 'BK', 'B#'), ('BU', 'BB', 'BP'), ('BQ', 'BH', 'BZ'),
            ('BT', 'BF', 'BM'), ('BK', 'BA', 'BR'), ('B#', 'BA', 'BB'), (), (),),
    '209': (('BA', 'BD', 'BG'), ('BL', 'BP', 'BK'), ('BH', 'BA', 'BC'), ('BG', 'BJ', 'BV'), ('BO', 'BS', 'BE'),
            ('BY', 'B#', 'BN'), ('BZ', 'BE', 'BK'), ('BF', 'BY', 'BQ'), ('BH', 'BM', 'BR'), ('BB', 'BT', 'BK'),
            ('BE', 'BI', 'BY'), ('BX', 'BQ', 'BG'), ('BU', 'BV', 'BW'), (), (),),
    '210': (('BB', 'BE', 'BH'), ('BV', 'BZ', 'BR'), ('BP', 'BI', 'BN'), ('BA', 'BM', 'BY'), ('BJ', 'BW', 'BF'),
            ('BV', 'BF', 'BK'), ('BM', 'BS', 'BG'), ('BH', 'BX', 'BP'), ('BJ', 'BX', 'BE'), ('BU', 'BL', 'BC'),
            ('BD', 'BK', 'BX'), ('BJ', 'B#', 'BT'), ('BO', 'BP', 'BQ'), (), (),),
    '211': (('BT', 'BW', 'BZ'), ('BC', 'BG', 'BB'), ('BQ', 'BJ', 'BL'), ('B#', 'BL', 'BX'), ('BI', 'BV', 'BH'),
            ('BT', 'BD', 'BO'), ('BY', 'BD', 'BJ'), ('BM', 'BE', 'BU'), ('BI', 'BZ', 'BD'), ('BW', 'BN', 'BE'),
            ('BR', 'BG', 'BN'), ('BZ', 'BP', 'BF'), ('BR', 'BS', 'BT'), (), (),),
    'Cafe': (('B#', 'BC', 'BF'), ('BW', 'BX', 'BS'), ('BY', 'BR', 'BW'), ('BD', 'BP', 'BS'), ('BL', 'BY', 'BB'),
             ('BU', 'BH', 'BJ'), ('BN', 'BT', 'BH'), ('BG', 'BZ', 'BO'), ('BV', 'B#', 'BQ'), ('BV', 'BM', 'BD'),
             ('BQ', 'BU', 'BA'), ('BI', 'BB', 'BS'), ('BI', 'BJ', 'BK'), (), (),),
}

quizzes_afternoon2 = {
    ('101', 1): ('', '', ''),
    ('102', 1): ('', '', ''),
    ('103', 1): ('', '', ''),
    ('104', 1): ('', '', ''),
    ('105', 1): ('', '', ''),
    ('106', 1): ('', '', ''),
    ('205', 1): ('', '', ''),
    ('206', 1): ('', '', ''),
    ('213', 1): ('', '', ''),
    ('202', 1): ('', '', ''),
    ('203', 1): ('', '', ''),
    ('204', 1): ('', '', ''),
    ('207', 1): ('', '', ''),
    ('208', 1): ('', '', ''),
    ('209', 1): ('', '', ''),
    ('210', 1): ('', '', ''),
    ('211', 1): ('', '', ''),
    ('Cafe', 1): ('', '', ''),
    ('101', 2): ('', '', ''),
    ('102', 2): ('', '', ''),
    ('103', 2): ('', '', ''),
    ('104', 2): ('', '', ''),
    ('105', 2): ('', '', ''),
    ('106', 2): ('', '', ''),
    ('205', 2): ('', '', ''),
    ('206', 2): ('', '', ''),
    ('213', 2): ('', '', ''),
    ('202', 2): ('', '', ''),
    ('203', 2): ('', '', ''),
    ('204', 2): ('', '', ''),
    ('207', 2): ('', '', ''),
    ('208', 2): ('', '', ''),
    ('209', 2): ('', '', ''),
    ('210', 2): ('', '', ''),
    ('211', 2): ('', '', ''),
    ('Cafe', 2): ('', '', ''),
    ('101', 3): ('', '', ''),
    ('102', 3): ('', '', ''),
    ('103', 3): ('', '', ''),
    ('104', 3): ('', '', ''),
    ('105', 3): ('', '', ''),
    ('106', 3): ('', '', ''),
    ('205', 3): ('', '', ''),
    ('206', 3): ('', '', ''),
    ('213', 3): ('', '', ''),
    ('202', 3): ('', '', ''),
    ('203', 3): ('', '', ''),
    ('204', 3): ('', '', ''),
    ('207', 3): ('', '', ''),
    ('208', 3): ('', '', ''),
    ('209', 3): ('', '', ''),
    ('210', 3): ('', '', ''),
    ('211', 3): ('', '', ''),
    ('Cafe', 3): ('', '', ''),
    ('101', 4): ('', '', ''),
    ('102', 4): ('', '', ''),
    ('103', 4): ('', '', ''),
    ('104', 4): ('', '', ''),
    ('105', 4): ('', '', ''),
    ('106', 4): ('', '', ''),
    ('205', 4): ('', '', ''),
    ('206', 4): ('', '', ''),
    ('213', 4): ('', '', ''),
    ('202', 4): ('', '', ''),
    ('203', 4): ('', '', ''),
    ('204', 4): ('', '', ''),
    ('207', 4): ('', '', ''),
    ('208', 4): ('', '', ''),
    ('209', 4): ('', '', ''),
    ('210', 4): ('', '', ''),
    ('211', 4): ('', '', ''),
    ('Cafe', 4): ('', '', ''),
    ('101', 5): ('', '', ''),
    ('102', 5): ('', '', ''),
    ('103', 5): ('', '', ''),
    ('104', 5): ('', '', ''),
    ('105', 5): ('', '', ''),
    ('106', 5): ('', '', ''),
    ('205', 5): ('', '', ''),
    ('206', 5): ('', '', ''),
    ('213', 5): ('', '', ''),
    ('202', 5): ('', '', ''),
    ('203', 5): ('', '', ''),
    ('204', 5): ('', '', ''),
    ('207', 5): ('', '', ''),
    ('208', 5): ('', '', ''),
    ('209', 5): ('', '', ''),
    ('210', 5): ('', '', ''),
    ('211', 5): ('', '', ''),
    ('Cafe', 5): ('', '', ''),
    ('101', 6): ('', '', ''),
    ('102', 6): ('', '', ''),
    ('103', 6): ('', '', ''),
    ('104', 6): ('', '', ''),
    ('105', 6): ('', '', ''),
    ('106', 6): ('', '', ''),
    ('205', 6): ('', '', ''),
    ('206', 6): ('', '', ''),
    ('213', 6): ('', '', ''),
    ('202', 6): ('', '', ''),
    ('203', 6): ('', '', ''),
    ('204', 6): ('', '', ''),
    ('207', 6): ('', '', ''),
    ('208', 6): ('', '', ''),
    ('209', 6): ('', '', ''),
    ('210', 6): ('', '', ''),
    ('211', 6): ('', '', ''),
    ('Cafe', 6): ('', '', ''),
    ('101', 7): ('', '', ''),
    ('102', 7): ('', '', ''),
    ('103', 7): ('', '', ''),
    ('104', 7): ('', '', ''),
    ('105', 7): ('', '', ''),
    ('106', 7): ('', '', ''),
    ('205', 7): ('', '', ''),
    ('206', 7): ('', '', ''),
    ('213', 7): ('', '', ''),
    ('202', 7): ('', '', ''),
    ('203', 7): ('', '', ''),
    ('204', 7): ('', '', ''),
    ('207', 7): ('', '', ''),
    ('208', 7): ('', '', ''),
    ('209', 7): ('', '', ''),
    ('210', 7): ('', '', ''),
    ('211', 7): ('', '', ''),
    ('Cafe', 7): ('', '', ''),
}

quizzes_afternoon3 = {
    ('208', 1): ('', '', ''),
    ('210', 1): ('', '', ''),
    ('208', 2): ('', '', ''),
    ('101', 1): ('', '', ''),
    ('104', 1): ('', '', ''),
    ('101', 2): ('', '', ''),
    ('206', 1): ('', '', ''),
    ('203', 1): ('', '', ''),
    ('205', 1): ('', '', ''),
    ('Cafe', 1): ('', '', ''),
    ('203', 2): ('', '', ''),
    ('205', 2): ('', '', ''),
    ('Cafe', 2): ('', '', ''),
    ('203', 3): ('', '', ''),
    ('205', 3): ('', '', ''),
    ('Cafe', 3): ('', '', ''),
    ('203', 4): ('', '', ''),
    ('205', 4): ('', '', ''),
    ('Cafe', 4): ('', '', ''),
    ('203', 5): ('', '', ''),
    ('205', 5): ('', '', ''),
    ('Cafe', 5): ('', '', ''),
    ('203', 6): ('', '', ''),
    ('205', 6): ('', '', ''),
    ('Cafe', 6): ('', '', ''),
    ('203', 7): ('', '', ''),
    ('205', 7): ('', '', ''),
    ('Cafe', 7): ('', '', ''),
    ('203', 8): ('', '', ''),
    ('205', 8): ('', '', ''),
    ('Cafe', 8): ('', '', ''),
}

rooms = {
    '101': ('Nathan Ashmore', 'Lloyd Myers'),
    '102': ('Laura Townsend', 'Debbie Eastland'),
    '103': ('Matthew Farmer', 'Michele Barr'),
    '104': ('Tim Selby', 'Heather Crosby'),
    '105': ('Nathan Crosby', 'Hannah Grimm'),
    '106': ('David Allgood', 'Carlos Fonte'),
    '205': ('Dalton Croy', 'Sarah Handal'),
    '211': ('Roscoe Ziemer', 'Naomi Davis'),
    '213': ('Jim Knudsen', 'Paul Crosby'),
    '202': ('William Hales', 'Robyn Douglas'),
    '203': ('Daniel Jones', 'Stephen Eastland'),
    '204': ('Matthew Myers', 'Karen Simmons'),
    '207': ('Doug Thomas', 'Danielle Crosby'),
    '208': ('George Wood', 'Marj Wood'),
    '209': ('Andy Petersen', 'Austin Handal'),
    '210': ('Doug Raynes', 'David Crosby'),
    '206': ('Marian Douglas', 'Sherri Crosby'),
    'Cafe': ('Cullen Baggett', 'Victoria Eastland'),
}

progressions = [
    {'type': 'tiebreaker', 'quiz': None, 'division': 1, 'rank': 8, 'next_quiz': 252, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'tiebreaker', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 250, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'tiebreaker', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 266, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'tiebreaker', 'quiz': None, 'division': 2, 'rank': 8, 'next_quiz': 245, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'tiebreaker', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 241, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'tiebreaker', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 242, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 8, 'next_quiz': 270, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 8, 'next_quiz': 270, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 266, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 266, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 281, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 281, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 281, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 282, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 282, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 282, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 277, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 277, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 277, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 279, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 279, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 279, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 288, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 288, 'next_division': 3,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 299, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 299, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 299, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 300, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 300, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 300, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 295, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 295, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 295, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 297, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 297, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 297, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 306, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 306, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 306, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 317, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 317, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 317, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 318, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 318, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 318, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 313, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 313, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 313, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 315, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 315, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 315, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 324, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 324, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 324, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 335, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 335, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 335, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 336, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 336, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 336, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 331, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 331, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 331, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 333, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 333, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 333, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 342, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 342, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 342, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 353, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 353, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 353, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 354, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 354, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 354, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 349, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 349, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 349, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 351, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 351, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 351, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 360, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 360, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 360, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 371, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 371, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 371, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 372, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 372, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 372, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 367, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 367, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 367, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 369, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 369, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 369, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 378, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 378, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 378, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 5, 'next_quiz': 389, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 1, 'next_quiz': 389, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 1, 'next_quiz': 389, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 390, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 5, 'next_quiz': 390, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 2, 'next_quiz': 390, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 3, 'next_quiz': 390, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 3, 'next_quiz': 385, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 7, 'next_quiz': 385, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 2, 'next_quiz': 387, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 4, 'next_quiz': 387, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 6, 'next_quiz': 387, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 4, 'next_quiz': 396, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 7, 'next_quiz': 396, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 6, 'next_quiz': 396, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 280, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 280, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 280, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 283, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 283, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 283, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 284, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 284, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 284, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 285, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 285, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 285, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 286, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 286, 'next_division': 4,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 298, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 298, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 298, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 301, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 301, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 301, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 302, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 302, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 302, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 303, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 303, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 303, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 304, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 304, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 304, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 316, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 316, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 316, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 319, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 319, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 319, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 320, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 320, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 320, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 321, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 321, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 321, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 322, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 322, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 322, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 334, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 334, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 334, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 337, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 337, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 337, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 338, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 338, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 338, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 339, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 339, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 339, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 340, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 340, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 340, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 352, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 352, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 352, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 355, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 355, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 355, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 356, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 356, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 356, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 357, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 357, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 357, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 358, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 358, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 358, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 370, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 370, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 370, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 373, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 373, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 373, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 374, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 374, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 374, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 375, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 375, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 375, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 376, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 376, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 376, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 13, 'next_quiz': 388, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 9, 'next_quiz': 388, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 9, 'next_quiz': 388, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 391, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 13, 'next_quiz': 391, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 10, 'next_quiz': 391, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 11, 'next_quiz': 391, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 11, 'next_quiz': 392, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 15, 'next_quiz': 392, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 10, 'next_quiz': 393, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 12, 'next_quiz': 393, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 14, 'next_quiz': 393, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 12, 'next_quiz': 394, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 15, 'next_quiz': 394, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 14, 'next_quiz': 394, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 8, 'division': 1, 'rank': 17, 'next_quiz': 271, 'next_division': 5, 'isCompleted': False,
     'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 271, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 271, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 272, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 272, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 272, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 273, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 273, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 273, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 274, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 274, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 274, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 275, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 275, 'next_division': 5,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 289, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 289, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 289, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 290, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 290, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 290, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 291, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 291, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 291, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 292, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 292, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 292, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 293, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 293, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 293, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 307, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 307, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 307, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 308, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 308, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 308, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 309, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 309, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 309, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 310, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 310, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 310, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 311, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 311, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 311, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 325, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 325, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 325, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 326, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 326, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 326, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 327, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 327, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 327, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 328, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 328, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 328, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 329, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 329, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 329, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 343, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 343, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 343, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 344, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 344, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 344, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 345, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 345, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 345, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 346, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 346, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 346, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 347, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 347, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 347, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 361, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 361, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 361, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 362, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 362, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 362, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 363, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 363, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 363, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 364, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 364, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 364, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 365, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 365, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 365, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 21, 'next_quiz': 379, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 17, 'next_quiz': 379, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 17, 'next_quiz': 379, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 380, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 21, 'next_quiz': 380, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 18, 'next_quiz': 380, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 19, 'next_quiz': 380, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 19, 'next_quiz': 381, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 23, 'next_quiz': 381, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 18, 'next_quiz': 382, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 20, 'next_quiz': 382, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 22, 'next_quiz': 382, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 20, 'next_quiz': 383, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 23, 'next_quiz': 383, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 22, 'next_quiz': 383, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 1, 'next_quiz': 288, 'next_division': 3,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': 270, 'division': None, 'rank': 2, 'next_quiz': 286, 'next_division': 4,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 1, 'next_quiz': 275, 'next_division': 5,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 2, 'next_quiz': 276, 'next_division': 6,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 24, 'next_quiz': 276, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 25, 'next_quiz': 276, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 26, 'next_quiz': 287, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 27, 'next_quiz': 287, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 24, 'next_quiz': 287, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 25, 'next_quiz': 278, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 26, 'next_quiz': 278, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 27, 'next_quiz': 278, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 2, 'next_quiz': 294, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 26, 'next_quiz': 294, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 25, 'next_quiz': 294, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 24, 'next_quiz': 305, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 27, 'next_quiz': 305, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 26, 'next_quiz': 305, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 25, 'next_quiz': 296, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 24, 'next_quiz': 296, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 27, 'next_quiz': 296, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 2, 'next_quiz': 312, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 27, 'next_quiz': 312, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 27, 'next_quiz': 312, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 24, 'next_quiz': 323, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 24, 'next_quiz': 323, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 25, 'next_quiz': 323, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 25, 'next_quiz': 314, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 26, 'next_quiz': 314, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 26, 'next_quiz': 314, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': 266, 'division': None, 'rank': 2, 'next_quiz': 330, 'next_division': None,
     'isCompleted': False, 'allow_ties': False},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 24, 'next_quiz': 330, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 26, 'next_quiz': 330, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 24, 'next_quiz': 341, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 26, 'next_quiz': 341, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 27, 'next_quiz': 341, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 25, 'next_quiz': 332, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 1, 'rank': 27, 'next_quiz': 332, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
    {'type': 'normal', 'quiz': None, 'division': 2, 'rank': 25, 'next_quiz': 332, 'next_division': None,
     'isCompleted': False, 'allow_ties': True},
]
