name: Django CI/CD

on:
  push:
    branches: [ "sandbox" ]
  pull_request:
    branches: [ "sandbox" ]

jobs:
  run_tests:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set Env Vars From Secret
      run:
        source QuizSite/.env

    - name: Run Tests
      run: |
        python manage.py test


  deploy:
    needs: run_tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Update Local Git Repository
        run: |
          git fetch
          git reset --hard origin/sandbox
      - name: Set up Python Environment
        run: | 
          pip install -r requirements.txt
      - name: Migrate Database
        run: |
          python3 manage.py migrate
      - name: Collect Static Files
        run: |
          python3 manage.py collectstatic --noinput
      - name: Restart Nginx and Gunicorn
        run: |
          sudo systemctl restart nginx 
          sudo systemctl restart gunicorn
